### ISSUE TITLE
how to use translate by cli command

### ISSUE THREAD

**Issue by houoop** [abdeladim-s/subsai#11]
I use this command 
subsai -f srt --model ggerganov/whisper.cpp --model-configs '{"model_type": "base.en","n_threads":10}' --translation-configs '{"type": "facebook/m2m100_418M"}' -tsl English -ttl Chinese  111.avi
It run , only generate srt , not translate.

**Comment by abdeladim-s** [comment]
@alfuraiji, are there any issues with the command suggested ?

**Comment by alfuraiji** [comment]
> @alfuraiji, are there any issues with the command suggested?

Yeah I was working with Japanese audio to Arabic sub .. and I figured it out my problem was with the language code because "Arabic" didn't work with nllb-200-distilled-600m but here is the correct code 

` subsai /localdata/01.mp4 --model openai/whisper --model-configs '{"model_type":"large-v3","language":"Japanese","task":"translate"}' --translation-model facebook/nllb-200-distilled-600M -tsl English -ttl arb_Arab --format srt`

also I 've found the language codes here in this one 
https://gist.github.com/tos-kamiya/033d016094d0570e514a867fd37c21a9

I think the documentation should provide some long examples like mine 

because I still don't know how to do the  --translation-configs in the correct way.

**Comment by abdeladim-s** [comment]
I think all the CLI options are fully documented, you can check this out by running it with `--help`. 
But We can add this example to the readme page as well for more clarification. 
You can send a PR for this, otherwise I'll add it later myself. 
Thanks.

---

For the translation config, it's easy, almost the same way as what you did with model-configs, you use `--translation-configs '{}'` with a json string.
